spring:
  application:
    name: productservice
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/product_management
    username: root
    password: root@123
  config:
    import: optional:configserver:http://172.18.0.1:9400/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

flyway:
  user: root
  password: root@123
  schemas: product_management
  baselineOnMigrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false